<?php
if (!defined('ABSPATH')) exit;
function nexora_setup(){add_theme_support('title-tag');add_theme_support('post-thumbnails');add_theme_support('html5',array('search-form','comment-form','gallery','caption','style','script'));register_nav_menus(array('primary'=>'Primary Menu'));}
add_action('after_setup_theme','nexora_setup');
function nexora_assets(){wp_enqueue_style('nexora-style',get_stylesheet_uri(),array(),'1.0.0');wp_enqueue_script('nexora-main',get_template_directory_uri().'/assets/main.js',array(),'1.0.0',true);}
add_action('wp_enqueue_scripts','nexora_assets');
function nexora_menu_fallback(){echo '<a href="'.esc_url(home_url('/')).'">Home</a><a href="'.esc_url(home_url('/about/')).'">About</a><a href="'.esc_url(home_url('/services/')).'">Services</a><a href="'.esc_url(home_url('/projects/')).'">Projects</a><a href="'.esc_url(home_url('/blog/')).'">Blog</a><a href="'.esc_url(home_url('/contact/')).'">Contact</a>';}
function nexora_page_intro($label,$title,$text){echo '<section class="page-hero"><div class="container"><p class="eyebrow">'.esc_html($label).'</p><h1 class="display">'.esc_html($title).'</h1><p class="lead">'.esc_html($text).'</p></div></section>';}
function nexora_seed_theme(){
 $pages=['Home'=>'home','About'=>'about','Services'=>'services','Projects'=>'projects','Blog'=>'blog','Contact'=>'contact'];$ids=[];
 foreach($pages as $title=>$slug){$page=get_page_by_path($slug);$ids[$title]=$page?$page->ID:wp_insert_post(['post_title'=>$title,'post_name'=>$slug,'post_status'=>'publish','post_type'=>'page']);}
 update_option('show_on_front','page');update_option('page_on_front',$ids['Home']);update_option('page_for_posts',$ids['Blog']);update_option('blogname','Nexora Digital');update_option('blogdescription','Building Digital Experiences That Move Businesses Forward.');update_option('permalink_structure','/%postname%/');
 $posts=['How Website Performance Affects User Experience'=>'A fast website is a basic part of a good customer experience.<h2>Speed shapes first impressions</h2><p>A responsive interface communicates care and competence, while delays introduce doubt.</p><h2>Performance supports accessibility</h2><p>Lean pages work better on older devices and inconsistent mobile connections.</p><h2>Start with the essentials</h2><p>Measure real pages, compress media, limit unnecessary plugins and prioritize the content users need first.</p>','5 Things Every Modern Business Website Needs'=>'A useful business website needs a few fundamentals executed consistently.<h2>1. A clear promise</h2><p>Tell visitors what you do and why it matters.</p><h2>2. Intentional navigation</h2><p>Use familiar labels and clear actions.</p><h2>3. Responsive layouts</h2><p>Design for mobile constraints.</p><h2>4. Evidence</h2><p>Projects and grounded testimonials help people assess fit.</p><h2>5. Strong foundations</h2><p>Accessibility, performance and search visibility are part of the product.</p>','WordPress vs Custom Development: Which Should You Choose?'=>'The right choice depends on how your team will publish, maintain and extend the website.<h2>When WordPress fits</h2><p>WordPress suits content-rich sites that need flexible publishing.</p><h2>When custom development fits</h2><p>A custom application makes sense when workflows and interactions are product-specific.</p><h2>A practical decision</h2><p>Consider editor needs, integrations, budget, ownership and expected lifetime.</p>'];
 foreach($posts as $title=>$content){if(!get_page_by_title($title,OBJECT,'post'))wp_insert_post(['post_title'=>$title,'post_content'=>$content,'post_excerpt'=>wp_strip_all_tags(strtok($content,'<')),'post_status'=>'publish','post_type'=>'post']);}
 $menu=wp_get_nav_menu_object('Primary');$mid=$menu?$menu->term_id:wp_create_nav_menu('Primary');foreach($pages as $title=>$slug){$found=false;foreach((array)wp_get_nav_menu_items($mid) as $item){if((int)$item->object_id===(int)$ids[$title])$found=true;}if(!$found)wp_update_nav_menu_item($mid,0,['menu-item-title'=>$title,'menu-item-object'=>'page','menu-item-object-id'=>$ids[$title],'menu-item-type'=>'post_type','menu-item-status'=>'publish']);}set_theme_mod('nav_menu_locations',['primary'=>$mid]);flush_rewrite_rules();
}
add_action('after_switch_theme','nexora_seed_theme');
