<?php
/* Plugin Name: Nexora Site Setup
Description: Creates the Nexora Digital demo pages, posts, settings and navigation.
Version: 1.0.0 */
if(!defined('ABSPATH'))exit;
function nexora_seed_site(){
 $pages=['Home'=>'','About'=>'about','Services'=>'services','Projects'=>'projects','Blog'=>'blog','Contact'=>'contact'];$ids=[];
 foreach($pages as $title=>$slug){$existing=get_page_by_path($slug?:'home');if(!$existing){$id=wp_insert_post(['post_title'=>$title,'post_name'=>$slug?:'home','post_status'=>'publish','post_type'=>'page','post_content'=>'']);}else{$id=$existing->ID;}$ids[$title]=$id;}
 update_option('show_on_front','page');update_option('page_on_front',$ids['Home']);update_option('page_for_posts',$ids['Blog']);update_option('blogname','Nexora Digital');update_option('blogdescription','Building Digital Experiences That Move Businesses Forward.');update_option('permalink_structure','/%postname%/');
 $posts=[
 'How Website Performance Affects User Experience'=>'A fast website is more than a technical achievement—it is a basic part of a good customer experience. Slow pages interrupt attention, reduce trust and make every next step feel harder.<h2>Speed shapes first impressions</h2><p>Visitors form an opinion before they have read the headline. A responsive interface communicates care and competence, while delays introduce doubt.</p><h2>Performance supports accessibility</h2><p>Lean pages work better on older devices and inconsistent mobile connections. Optimizing images, fonts and scripts makes the experience more inclusive.</p><h2>Start with the essentials</h2><p>Measure real pages, compress media, limit unnecessary plugins and prioritize the content users need first.</p>',
 '5 Things Every Modern Business Website Needs'=>'A useful business website does not need endless features. It needs a small number of fundamentals executed consistently.<h2>1. A clear promise</h2><p>Tell visitors what you do, who it is for and why it matters.</p><h2>2. Intentional navigation</h2><p>Use familiar labels and give every page a clear next action.</p><h2>3. Responsive layouts</h2><p>Design for the constraints of mobile instead of shrinking a desktop page.</p><h2>4. Evidence</h2><p>Projects, useful numbers and grounded testimonials help people assess fit.</p><h2>5. Strong foundations</h2><p>Accessibility, performance and search visibility are part of the product—not finishing touches.</p>',
 'WordPress vs Custom Development: Which Should You Choose?'=>'The right choice depends less on fashion and more on how your team will publish, maintain and extend the website.<h2>When WordPress fits</h2><p>WordPress is a strong option for content-rich marketing sites that need flexible publishing and a familiar editor.</p><h2>When custom development fits</h2><p>A custom application makes sense when workflows, data or interactions are truly product-specific.</p><h2>A practical decision</h2><p>Consider editor needs, integrations, budget, ownership and the expected lifetime of the platform before choosing the stack.</p>'];
 foreach($posts as $title=>$content){if(!get_page_by_title($title,OBJECT,'post'))wp_insert_post(['post_title'=>$title,'post_content'=>$content,'post_excerpt'=>wp_strip_all_tags(strtok($content,'<')),'post_status'=>'publish','post_type'=>'post']);}
 $menu=wp_get_nav_menu_object('Primary');$menu_id=$menu?$menu->term_id:wp_create_nav_menu('Primary');foreach($pages as $title=>$slug){$present=wp_get_nav_menu_items($menu_id);$exists=false;foreach((array)$present as $item){if((int)$item->object_id===(int)$ids[$title])$exists=true;}if(!$exists)wp_update_nav_menu_item($menu_id,0,['menu-item-title'=>$title,'menu-item-object'=>'page','menu-item-object-id'=>$ids[$title],'menu-item-type'=>'post_type','menu-item-status'=>'publish']);}
 set_theme_mod('nav_menu_locations',['primary'=>$menu_id]);flush_rewrite_rules();
}
register_activation_hook(__FILE__,'nexora_seed_site');
